# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ynv < Formula
  desc ""
  homepage "https://github.com/snooc/ynv"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/snooc/ynv/releases/download/v0.1.1/ynv_Darwin_x86_64.tar.gz"
      sha256 "d3f5f8fce77a87540adaea83e803b22485384143c757d1d45f1a5dd3b2bda60e"

      def install
        bin.install "ynv"
      end
    end
    on_arm do
      url "https://github.com/snooc/ynv/releases/download/v0.1.1/ynv_Darwin_arm64.tar.gz"
      sha256 "76051ed647be7d5acc49ad10c0c6d51eda0c6d4a22ca5f8440dffd54ec7c6afb"

      def install
        bin.install "ynv"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/snooc/ynv/releases/download/v0.1.1/ynv_Linux_x86_64.tar.gz"
        sha256 "0afdda68c9d478b555c19950ef589a86600ac78f4c72e4e002519038550365dd"

        def install
          bin.install "ynv"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/snooc/ynv/releases/download/v0.1.1/ynv_Linux_arm64.tar.gz"
        sha256 "4c7e0dd3553be9f51197855a36074401681c36a81f42fc60bc0badd30302bc2e"

        def install
          bin.install "ynv"
        end
      end
    end
  end
end
