# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ynv < Formula
  desc ""
  homepage "https://github.com/snooc/ynv"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/snooc/ynv/releases/download/v0.1.1/ynv_Darwin_x86_64.tar.gz"
      sha256 "9065ce4460bbb700b30fb44f905f0416051e6704da63fbfcb1a1f0c1c6e073e2"

      def install
        bin.install "ynv"
      end
    end
    on_arm do
      url "https://github.com/snooc/ynv/releases/download/v0.1.1/ynv_Darwin_arm64.tar.gz"
      sha256 "ada9a1ece3dfb331ec28c4aa49c573e198a3db4eafd90aa0eda0d9d5571c278f"

      def install
        bin.install "ynv"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/snooc/ynv/releases/download/v0.1.1/ynv_Linux_x86_64.tar.gz"
        sha256 "6e9b4de8b178ed659bb02ccf21493eb60784c52c4e39c0791e1724778de48d9f"

        def install
          bin.install "ynv"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/snooc/ynv/releases/download/v0.1.1/ynv_Linux_arm64.tar.gz"
        sha256 "015a0868b3db7c09b0f117055dbdd8c71a46513a6df626997eb61e460b69a299"

        def install
          bin.install "ynv"
        end
      end
    end
  end
end
